### ISSUE TITLE
Text color doesn't change for the 0 button

### ISSUE THREAD

**Issue by Yasir5247** [anhnch/react-native-pin-code#3]
Hi,
Thank you for the library. Text color doesn't change for the 0 button.
![Screenshot 2022-07-24 at 10 18 53](https://user-images.githubusercontent.com/472971/180634481-782708d6-4663-4eb7-813e-35eb55a2ff2f.png)

**Comment by Yasir5247** [comment]
Also, how to set a left button?

**Comment by anhnch** [comment]
> Hi, Thank you for the library. Text color doesn't change for the 0 button. ![Screenshot 2022-07-24 at 10 18 53](https://user-images.githubusercontent.com/472971/180634481-782708d6-4663-4eb7-813e-35eb55a2ff2f.png)

Yes, it's a bug. It'll be fixed in the next release

**Comment by anhnch** [comment]
> Also, how to set a left button?

What do you mean by the left button? Do you mean the Back button? This is the lock screen. It's meant not able to go back.

**Comment by Yasir5247** [comment]
![Screenshot 2022-08-01 at 20 36 37](https://user-images.githubusercontent.com/472971/182186520-b8524840-49f5-43e3-8534-c68149386956.png)

**Comment by Yasir5247** [comment]
left button as in there. when i can i expect for the next update. thank you for the library.

**Comment by ajayesivan** [comment]
Hi @anhnch,
I have created a PR with a fix for this issue. Could you please review it?
